### ISSUE TITLE
const params = paramNames?.trim().split(/\s+/) ?? [];

### ISSUE THREAD

**Issue by iqbalnur32** [RioChndr/jaksel-language#52]
hallo bang kenapa di saya ketika saya jalankan untuk example1.jaksel muncul error

> /usr/lib/node_modules/jaksel-language/lib/logics/parser/functionDeclarationBegin.js:11
  const params = paramNames?.trim().split(/\s+/) ?? [];
                            ^
>SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/jaksel-language/lib/logics/index.js:10:34)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

saya menggunkaan node version 12.12, apakah tidak support di version node tersebut
di beberapa command seperti 
>jaksel example/example2.jaksel 

ataupun menggunakan command

>node jaksel-interpreter.js example/example2.jaksel

**Comment by RioChndr** [comment]
Coba versi terbaru, v16.10
